POST http://localhost:3001/api/user/changeStudentNumber
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZmIxMjkyOTA5NzkyMDQzNTRlY2RiZGYiLCJpYXQiOjE2MDU0NDU5Mzh9.y94kx-mvD5ueG5rGhZIQeQAfMuB3KaLlgcJwNh7BCD0

{
    "password":"admin",
    "newStudentNumber": "123456567"
}