PUT http://localhost:3001/api/user
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZmMwMTBlODMyNGY4NDJkMWM2NDFmYzkiLCJpYXQiOjE2MDY0MjI3NjZ9.8BLhNIwpAO1H471jZAWY7MuH7UtDcYV5CuC7NTlneZ4

{
    "password":"adminadmin",
    "newClassGroup": "C-1234456"
}