POST http://localhost:3001/api/user/changePassword
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZmIxMWNjY2UxZDQzMzUzNzA2OGFjYWMiLCJpYXQiOjE2MDU0NDI3NzB9.5qoPb48FJpCK_4JxhSCkqjtSiHME70tx5s-CibkzRuY

{
    "password": "admin",
    "newPassword": "newPassword"
