GET http://localhost:3001/api/bacteria
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1ZjYwOTQyYjRkOWNlNDNjMDRhOGRiOTciLCJpYXQiOjE2MDAxNjQ5NTd9.8kBk5ZFBYZOXIfWilBRRW6s6VITRsRGxDZ4ijLnAxbk
