GET http://localhost:3001/api/credits
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI1Zjk1ODg4Y2UxZjYzNjA2OWMxMjA4MmIiLCJpYXQiOjE2MDM2MzUzODJ9.eyTtD85Nm-O32nikJAwIl6wU8ES7ZciAYgdNBGwfSW8