PUT http://localhost:3001/api/user
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Im5ld1VzZXIiLCJpZCI6IjVmY2QxYjhkMDg0MjI2MzE4NDlmYTBiNSIsImlhdCI6MTYwNzI3NzQ1NX0.Zd2wbbJI3064j0Lhm1GqPQKcQ40QSajKXLLKHpn5j7I

{
    "password":"newGoodPassword123",
    "newStudentNumber": null,
    "newClassGroup": null
}