PUT http://localhost:3001/api/bacteria/1
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXJuYW1lIiwiaWF0IjoxNjAwMDY5NDE2fQ.zemM8K-h9OBp2tCsBZOqH_stYxQAoBBlGqhIdW_KNsI

{
    "name": "kilo"
}