describe('Playing game', () => {
    beforeEach(() => {
        cy.request('POST', 'http://localhost:3001/api/testing/reset_bacteria')
        cy.request('POST', 'http://localhost:3001/api/testing/reset_tests')
        cy.request('POST', 'http://localhost:3001/api/testing/reset_cases')
        cy.request('POST', 'http://localhost:3001/api/testing/cases')
        cy.login({ username: 'admin', password: 'admin' })
        cy.visit('http://localhost:3000')
    })
    describe('Game can be played', () => {
        it('Admin can choose a case which to play', () => {
            cy.contains('Etusivu').click()
            cy.get('div').should('contain', 'Maitotila 1')
            cy.get('div').should('contain', 'Maitotila 2')
            cy.contains('Maitotila 1').click()
            cy.get('#samples').should('contain', 'Tankin maitonäyte')
            cy.get('#samples').should('contain', 'Maitonäyte Muurikin kaikista neljänneksistä')
            cy.get('#samples').should('contain', 'Ulostenäyte Muurikilta')
            cy.get('#samples').should('contain', 'Virtsanäyte Muurikilta')
        })

        it('Normal user can choose a case which to play', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.visit('http://localhost:3000')
            cy.contains('Etusivu').click()
            cy.get('div').should('contain', 'Maitotila 1')
            cy.get('div').should('not.contain', 'Maitotila 2')
            cy.contains('Maitotila 1').click()
            cy.get('#samples').should('contain', 'Tankin maitonäyte')
            cy.get('#samples').should('contain', 'Maitonäyte Muurikin kaikista neljänneksistä')
            cy.get('#samples').should('contain', 'Ulostenäyte Muurikilta')
            cy.get('#samples').should('contain', 'Virtsanäyte Muurikilta')
        })

        it('A valid samplingmethod can be chosen', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.get('div').should('contain','Tilalla on 27 lypsävää lehmää parsinavetassa ja lisäksi nuorkarjaa. Kuivikkeena käytetään kutteria, vesi tulee omasta kaivosta. Pääosa lehmistä on omaa tuotantoa, mutta navetan laajennuksen yhteydessä edellisenä kesänä hankittiin muutama uusi tiine eläin, jotka poikivat loppusyksystä.')
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.contains('Oikea vastaus')
        })

        it('If wrong samplingmethod is chosen, user is informed and right method can be chosen', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').first().check()
            cy.get('#checkSamples').click()
            cy.contains('Väärä vastaus')
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.contains('Väärä vastaus')
            cy.get('[type="checkbox"]').first().uncheck()
            cy.get('#checkSamples').click()
            cy.contains('Oikea vastaus')
        })

        it('After choosing right samplingmethod, user can choose all tests in required order', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.get('#testView').should('contain', 'Viljelyt')
            cy.get('#testView').should('contain', 'Testit')
            cy.get('#testView').should('contain', 'Värjäys')
            cy.contains('Testi ei kuulu testiryhmiin').click()
            // FIX THIS AFTER MORE INFORMATIVE MESSAGES ARE SET
            cy.contains('Väärä vastaus')
            cy.contains('CAMP-testi').click()
            // FIX THIS AFTER MORE INFORMATIVE MESSAGES ARE SET
            cy.contains('Väärä vastaus')
            cy.contains('Veriagar, +37 C, aerobinen kasvatus').click()
            cy.contains('Oikea vastaus')
            cy.contains('Gramvärjäys').click()
            cy.contains('Katalaasitesti').click()
            cy.contains('HIRS-sarja').click()
            cy.contains('Eskuliiniveriagar').click()
            cy.contains('Edwardsin agar').click()
            cy.contains('Lancefield määritys').click()
            cy.contains('Penisilliinin sietokoe agarvaluamenetelmällä').click()
            cy.contains('CAMP-testi').click()
            cy.contains('Oikea vastaus. Kaikki testit tehty.')
        })

        it('After choosing right samplingmethod, user can choose only required tests in required order', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.contains('Veriagar, +37 C, aerobinen kasvatus', { timeout: 5000 }).click()
            cy.contains('Gramvärjäys').click()
            cy.contains('Katalaasitesti').click()
            cy.contains('HIRS-sarja').click()
            cy.contains('Edwardsin agar').click()
            cy.contains('Penisilliinin sietokoe agarvaluamenetelmällä').click()
            cy.contains('Oikea vastaus. Kaikki vaaditut testit tehty.', { timeout: 5000 })
        })

        it('User can check control images of all tests', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.contains('Kontrolleja').click()
            cy.get('#controlImgTable').should('contain', 'Katalaasitesti')
            cy.get('#controlImgTable').should('contain', 'Veriagar, +37 C, aerobinen kasvatus')
            cy.get('#controlImgTable').should('contain', 'Edwardsin agar')
            cy.get('#controlImgTable').should('contain', 'HIRS-sarja')
            cy.get('#controlImgTable').should('contain', 'Penisilliinin sietokoe agarvaluamenetelmällä')
            cy.get('#controlImgTable').should('contain', 'CAMP-testi')
            cy.get('#controlImgTable').should('contain', 'Lancefield määritys')
            cy.get('#controlImgTable').should('contain', 'Eskuliiniveriagar')
            cy.get('#controlImgTable').should('contain', 'Gramvärjäys')
            cy.get('#controlImgTable').should('contain', 'Testi ei kuulu testiryhmiin')
        })

        it('User can see results after clicking a right test', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.contains('Veriagar, +37 C, aerobinen kasvatus').click()
            cy.contains('Tuloksia').click()
            cy.get('#resultTable').should('contain', 'Veriagar, +37 C, aerobinen kasvatus')
            cy.contains('Tuloksia').click()
            cy.get('#resultTable').should('not.contain', 'Gramvärjäys')
            cy.contains('Testejä').click()
            cy.contains('Gramvärjäys').click()
            cy.contains('Tuloksia').click()
            cy.get('#resultTable').should('contain', 'Gramvärjäys')
        })

        it('User can give diagnosis after choosing at least the required tests', () => {
            cy.login({ username: 'user', password: 'user' })
            cy.contains('Etusivu').click()
            cy.contains('Maitotila 1').click()
            cy.contains('Toiminnot').click()
            cy.get('[type="checkbox"]').eq('2').check()
            cy.get('#checkSamples').click()
            cy.contains('Veriagar, +37 C, aerobinen kasvatus').click()
            cy.contains('Gramvärjäys').click()
            cy.contains('Katalaasitesti').click()
            cy.contains('HIRS-sarja').click()
            cy.contains('Edwardsin agar').click()
            cy.contains('Penisilliinin sietokoe agarvaluamenetelmällä').click()
            cy.contains('Diagnoosi').click()
            cy.get('#bacterium').type('Tetanus')
            cy.get('#checkDiagnosis').click()
            cy.contains('Väärä vastaus')
            cy.get('#bacterium').clear().type('Streptococcus agalactiae')
            cy.get('#checkDiagnosis').click()
            cy.contains('Oikea vastaus')
            // Add should contain info
        })
    })

    after(() => {
        cy.request('POST', 'http://localhost:3001/api/testing/reset_bacteria')
        cy.request('POST', 'http://localhost:3001/api/testing/reset_tests')
        cy.request('POST', 'http://localhost:3001/api/testing/reset_cases')
    })
})